INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "./experiments"

# Evaluation datasets
GRABCUT_PATH: "/data/datasets/GrabCut"
BERKELEY_PATH: "/data/datasets/Berkeley"
DAVIS_PATH: "/data/datasets/DAVIS"
COCO_MVAL_PATH: "./datasets/COCO_MVal"

# Train datasets
SBD_PATH: "/data/datasets/SBD/dataset"
COCO_PATH: "/data/datasets/MS_COCO"
LVIS_PATH: "/data/datasets/LVIS"
LVIS_v1_PATH: "/data/datasets/LVIS"
OPENIMAGES_PATH: "./datasets/OpenImages"
PASCALVOC_PATH: "/data/datasets/VOCdevkit/VOC2012"
ADE20K_PATH: "./datasets/ADE20K"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "/data/pretrained/hrnet/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "/data/pretrained/hrnet/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
